import json
from pathlib import Path

import pytest

from aria.io import read_jsonl
from aria.pipeline import run_faithfulness_evaluation
from aria.schemas import Example, GeneratedTraceRecord, InterventionModelOutput, IntervenedTrace, JudgeOutput, StructuredTrace, TargetOutput


def test_faithfulness_evaluation_pipeline_writes_artifacts(tmp_path: Path) -> None:
    examples = example_records()

    summary = run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={"dataset": "scienceqa", "target_model": "target-model-under-test", "judge_model": "judge-model-under-test"},
        trace_generator=RecordingTraceGenerator(),
        judge=RecordingJudge(),
        target_evaluator=RecordingTargetEvaluator(),
    )

    assert summary["n_examples"] == 2
    assert (tmp_path / "processed_examples.jsonl").exists()
    assert (tmp_path / "original_traces.jsonl").exists()
    assert not (tmp_path / "generated_traces.jsonl").exists()
    assert (tmp_path / "intervened_traces.jsonl").exists()
    assert (tmp_path / "judge_outputs.jsonl").exists()
    assert (tmp_path / "target_outputs.jsonl").exists()
    assert (tmp_path / "target_effects.csv").exists()
    assert "dataset" in (tmp_path / "target_effects.csv").read_text(encoding="utf-8").splitlines()[0]
    assert (tmp_path / "mediation_metrics.csv").exists()
    assert (tmp_path / "metrics_summary.csv").exists()
    assert "answer_flip_rate_wrong_binding" in summary


class RecordingTraceGenerator:
    model_name = "recording-target"

    def __init__(self) -> None:
        self.calls = 0

    def generate_trace(self, example) -> StructuredTrace:
        self.calls += 1
        return StructuredTrace(
            visual_evidence=[{"modality": "image", "content": "The image contains the relevant visual evidence."}],
            textual_evidence=[{"modality": "text", "content": example.context or example.question}],
            binding_claim={
                "text": "The visual evidence is bound to the condition named in the question.",
                "bound_answer_option": example.correct_answer or "UNKNOWN",
            },
            scientific_principle={"text": "Use the supplied scientific principle."},
            inference={"text": "Apply the principle to the evidence."},
            conclusion=f"The reasoning supports answer {example.correct_answer or 'UNKNOWN'}.",
            final_answer=example.correct_answer or "UNKNOWN",
        )


class RecordingJudge:
    model_name = "recording-judge"

    def __init__(self) -> None:
        self.calls = 0

    def judge(self, intervention_id, trace, example) -> JudgeOutput:
        self.calls += 1
        return JudgeOutput(
            intervention_id=intervention_id,
            judge_model=self.model_name,
            faithfulness_score=5,
            is_intervened_or_flawed=False,
            flawed_component="none",
        )


class RecordingTargetEvaluator:
    model_name = "recording-target-rerun"

    def __init__(self) -> None:
        self.calls = 0

    def evaluate(self, intervention_id, trace, example, condition="original_trace", include_image=True) -> TargetOutput:
        self.calls += 1
        final_answer = trace.final_answer if trace is not None else example.correct_answer or "UNKNOWN"
        if trace is not None and condition == "retargeted_support":
            final_answer = trace.binding_claim.bound_answer_option or final_answer
        return TargetOutput(
            intervention_id=intervention_id,
            target_model=self.model_name,
            final_answer=final_answer,
            is_correct=final_answer == example.correct_answer if example.correct_answer else None,
            metadata={"condition": condition, "include_image": include_image},
        )


class RecordingInterventionModel:
    model_name = "recording-intervention"

    def __init__(self) -> None:
        self.calls = 0

    def generate_interventions(self, example, original_trace, template_records) -> InterventionModelOutput:
        self.calls += 1
        interventions = []
        for record in template_records:
            if record.intervention.intervention_type == "original_trace":
                continue
            interventions.append(
                {
                    "intervention_type": record.intervention.intervention_type,
                    "intervened_trace": record.intervened_trace.model_dump(mode="json"),
                    "notes": "generated by fake intervention model",
                }
            )
        return InterventionModelOutput(
            example_id=example.example_id,
            intervention_model=self.model_name,
            raw_output=json.dumps({"interventions": interventions}),
        )


class FailingSecondExampleInterventionModel(RecordingInterventionModel):
    def __init__(self, failing_example_id: str) -> None:
        super().__init__()
        self.failing_example_id = failing_example_id

    def generate_interventions(self, example, original_trace, template_records) -> InterventionModelOutput:
        if example.example_id == self.failing_example_id:
            raise RuntimeError("simulated intervention failure")
        return super().generate_interventions(example, original_trace, template_records)


def test_main_pipeline_uses_intervention_model_without_judge_artifact(tmp_path: Path) -> None:
    examples = example_records()[:1]
    intervention_model = RecordingInterventionModel()

    summary = run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={
            "dataset": "scienceqa",
            "target_model": "recording-target",
            "intervention_model": "recording-intervention",
            "include_retargeted_support": True,
        },
        trace_generator=RecordingTraceGenerator(),
        intervention_generator=intervention_model,
        target_evaluator=RecordingTargetEvaluator(),
    )

    assert intervention_model.calls == 1
    assert (tmp_path / "intervention_model_outputs.jsonl").exists()
    intervention_outputs = [json.loads(line) for line in (tmp_path / "intervention_model_outputs.jsonl").read_text().splitlines()]
    assert intervention_outputs[0]["interventions"] == []
    assert intervention_outputs[0]["raw_output"]
    assert not (tmp_path / "judge_outputs.jsonl").exists()
    assert "judge_model" in summary
    assert summary["intervention_model"] == "recording-intervention"


class RecordingCombinedTargetRunner(RecordingTraceGenerator):
    model_name = "recording-combined-target"

    def __init__(self) -> None:
        super().__init__()
        self.target_calls = 0
        self.unload_calls = 0
        self.unloaded = False

    def generate_trace(self, example) -> StructuredTrace:
        if self.unloaded:
            raise RuntimeError("combined runner was unloaded before trace generation")
        return super().generate_trace(example)

    def evaluate(self, intervention_id, trace, example, condition="original_trace", include_image=True) -> TargetOutput:
        if self.unloaded:
            raise RuntimeError("combined runner was unloaded before target rerun")
        self.target_calls += 1
        final_answer = trace.final_answer if trace is not None else example.correct_answer or "UNKNOWN"
        return TargetOutput(
            intervention_id=intervention_id,
            target_model=self.model_name,
            final_answer=final_answer,
            is_correct=final_answer == example.correct_answer if example.correct_answer else None,
            metadata={"condition": condition, "include_image": include_image},
        )

    def unload(self) -> None:
        self.unload_calls += 1
        self.unloaded = True


def test_faithfulness_evaluation_pipeline_accepts_injected_model_runners(tmp_path: Path) -> None:
    examples = example_records()[:1]
    trace_generator = RecordingTraceGenerator()
    judge = RecordingJudge()
    target_evaluator = RecordingTargetEvaluator()

    run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
        trace_generator=trace_generator,
        judge=judge,
        target_evaluator=target_evaluator,
    )

    assert trace_generator.calls == 1
    assert judge.calls > 0
    assert target_evaluator.calls > 0


def test_faithfulness_evaluation_pipeline_reuses_combined_target_runner_until_judge(tmp_path: Path) -> None:
    examples = example_records()[:1]
    target_runner = RecordingCombinedTargetRunner()

    run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
        trace_generator=target_runner,
        judge=RecordingJudge(),
        target_evaluator=target_runner,
    )

    assert target_runner.calls == 1
    assert target_runner.target_calls > 0
    assert target_runner.unload_calls == 1


def test_faithfulness_evaluation_pipeline_writes_modality_extension_artifacts(tmp_path: Path) -> None:
    examples = example_records()

    summary = run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={
            "dataset": "scienceqa",
            "target_model": "recording-target",
            "judge_model": "recording-judge",
            "include_modality_extension": True,
        },
        trace_generator=RecordingTraceGenerator(),
        judge=RecordingJudge(),
        target_evaluator=RecordingTargetEvaluator(),
    )

    target_outputs = read_jsonl(tmp_path / "target_outputs.jsonl", TargetOutput)
    judge_outputs = read_jsonl(tmp_path / "judge_outputs.jsonl", JudgeOutput)
    target_counts = _count_by_example_id(output.intervention_id for output in target_outputs)
    judge_counts = _count_by_example_id(output.intervention_id for output in judge_outputs)

    assert target_counts == {"scienceqa-test-1": 11, "scienceqa-test-2": 11}
    assert judge_counts == {"scienceqa-test-1": 8, "scienceqa-test-2": 8}
    assert (tmp_path / "modality_effects.csv").exists()
    assert (tmp_path / "modality_summary.csv").exists()
    assert "observed_reliance_label" in (tmp_path / "modality_effects.csv").read_text(encoding="utf-8").splitlines()[0]
    assert "n_modality_examples" in summary


def test_faithfulness_evaluation_pipeline_can_include_retargeted_support(tmp_path: Path) -> None:
    examples = example_records()

    summary = run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={
            "dataset": "scienceqa",
            "target_model": "recording-target",
            "judge_model": "recording-judge",
            "include_retargeted_support": True,
        },
        trace_generator=RecordingTraceGenerator(),
        judge=RecordingJudge(),
        target_evaluator=RecordingTargetEvaluator(),
    )

    target_outputs = read_jsonl(tmp_path / "target_outputs.jsonl", TargetOutput)
    judge_outputs = read_jsonl(tmp_path / "judge_outputs.jsonl", JudgeOutput)
    target_counts = _count_by_example_id(output.intervention_id for output in target_outputs)
    judge_counts = _count_by_example_id(output.intervention_id for output in judge_outputs)
    effects_header = (tmp_path / "target_effects.csv").read_text(encoding="utf-8").splitlines()[0]

    assert target_counts == {"scienceqa-test-1": 10, "scienceqa-test-2": 10}
    assert judge_counts == {"scienceqa-test-1": 7, "scienceqa-test-2": 7}
    assert "target_distractor" in effects_header
    assert "followed_retargeted_support" in effects_header
    assert summary["answer_flip_rate_retargeted_support"] == 1.0
    assert summary["retargeted_support_following_rate"] == 1.0


def test_faithfulness_evaluation_pipeline_checkpoints_completed_examples(tmp_path: Path) -> None:
    examples = example_records()

    with pytest.raises(RuntimeError, match="simulated target failure"):
        run_faithfulness_evaluation(
            examples=examples,
            output_dir=tmp_path,
            config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
            trace_generator=RecordingTraceGenerator(),
            judge=RecordingJudge(),
            target_evaluator=FailingSecondExampleTargetEvaluator("scienceqa-test-2"),
        )

    original_traces = read_jsonl(tmp_path / "original_traces.jsonl", GeneratedTraceRecord)
    intervened_records = read_jsonl(tmp_path / "intervened_traces.jsonl", IntervenedTrace)
    target_outputs = read_jsonl(tmp_path / "target_outputs.jsonl", TargetOutput)
    judge_outputs = read_jsonl(tmp_path / "judge_outputs.jsonl", JudgeOutput)
    status = json.loads((tmp_path / "run_status.json").read_text(encoding="utf-8"))

    assert len(original_traces) == 2
    assert {record.example_id for record in intervened_records} == {"scienceqa-test-1"}
    assert {output.intervention_id.split("::")[0] for output in target_outputs} == {"scienceqa-test-1"}
    assert judge_outputs == []
    assert status["completed_original_traces"] == 2
    assert status["completed_intervened_traces"] == 0
    assert status["completed_target_reruns"] == 1
    assert status["fully_completed_examples"] == 0
    assert status["stage"] == "target_rerun"
    assert (tmp_path / "checkpoints" / "examples" / "scienceqa-test-1" / "target_stage.json").exists()


def test_run_status_does_not_count_failed_intervention_checkpoints(tmp_path: Path) -> None:
    checkpoint_dir = tmp_path / "checkpoints" / "interventions"
    checkpoint_dir.mkdir(parents=True)
    (checkpoint_dir / "example-1.json").write_text("{}", encoding="utf-8")
    (checkpoint_dir / "example-2.failed.json").write_text("{}", encoding="utf-8")

    run_faithfulness_evaluation(
        examples=example_records()[:1],
        output_dir=tmp_path,
        config={"dataset": "scienceqa", "target_model": "recording-target"},
        trace_generator=RecordingTraceGenerator(),
        target_evaluator=RecordingTargetEvaluator(),
    )

    status = json.loads((tmp_path / "run_status.json").read_text(encoding="utf-8"))

    assert status["completed_intervened_traces"] == 1


def test_run_status_refreshes_during_intervention_generation(tmp_path: Path) -> None:
    examples = example_records()

    with pytest.raises(RuntimeError, match="simulated intervention failure"):
        run_faithfulness_evaluation(
            examples=examples,
            output_dir=tmp_path,
            config={
                "dataset": "scienceqa",
                "target_model": "recording-target",
                "intervention_model": "recording-intervention",
                "include_retargeted_support": True,
            },
            trace_generator=RecordingTraceGenerator(),
            intervention_generator=FailingSecondExampleInterventionModel("scienceqa-test-2"),
            target_evaluator=RecordingTargetEvaluator(),
        )

    status = json.loads((tmp_path / "run_status.json").read_text(encoding="utf-8"))

    assert status["stage"] == "intervention_generation"
    assert status["completed_original_traces"] == 2
    assert status["completed_intervened_traces"] == 1
    assert status["completed_target_reruns"] == 0


def test_faithfulness_evaluation_pipeline_reuses_trace_checkpoints_after_trace_failure(tmp_path: Path) -> None:
    examples = example_records()

    with pytest.raises(RuntimeError, match="simulated trace failure"):
        run_faithfulness_evaluation(
            examples=examples,
            output_dir=tmp_path,
            config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
            trace_generator=FailingSecondExampleTraceGenerator("scienceqa-test-2"),
            judge=RecordingJudge(),
            target_evaluator=RecordingTargetEvaluator(),
        )

    original_traces = read_jsonl(tmp_path / "original_traces.jsonl", GeneratedTraceRecord)
    assert [record.example_id for record in original_traces] == ["scienceqa-test-1"]

    trace_generator = RecordingTraceGenerator()
    run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
        trace_generator=trace_generator,
        judge=RecordingJudge(),
        target_evaluator=RecordingTargetEvaluator(),
    )

    assert trace_generator.calls == 1
    assert len(read_jsonl(tmp_path / "original_traces.jsonl", GeneratedTraceRecord)) == 2


def test_faithfulness_evaluation_pipeline_resumes_without_redoing_completed_examples(tmp_path: Path) -> None:
    examples = example_records()

    with pytest.raises(RuntimeError, match="simulated target failure"):
        run_faithfulness_evaluation(
            examples=examples,
            output_dir=tmp_path,
            config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
            trace_generator=RecordingTraceGenerator(),
            judge=RecordingJudge(),
            target_evaluator=FailingSecondExampleTargetEvaluator("scienceqa-test-2"),
        )

    trace_generator = RecordingTraceGenerator()
    judge = RecordingJudge()
    target_evaluator = RecordingTargetEvaluator()
    summary = run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
        trace_generator=trace_generator,
        judge=judge,
        target_evaluator=target_evaluator,
    )

    original_traces = read_jsonl(tmp_path / "original_traces.jsonl", GeneratedTraceRecord)
    target_outputs = read_jsonl(tmp_path / "target_outputs.jsonl", TargetOutput)
    judge_outputs = read_jsonl(tmp_path / "judge_outputs.jsonl", JudgeOutput)
    target_counts = _count_by_example_id(output.intervention_id for output in target_outputs)
    judge_counts = _count_by_example_id(output.intervention_id for output in judge_outputs)

    assert summary["n_examples"] == 2
    assert trace_generator.calls == 0
    assert judge.calls > 0
    assert target_evaluator.calls == 9
    assert len(original_traces) == 2
    assert target_counts == {"scienceqa-test-1": 9, "scienceqa-test-2": 9}
    assert judge_counts == {"scienceqa-test-1": 6, "scienceqa-test-2": 6}
    assert json.loads((tmp_path / "run_status.json").read_text(encoding="utf-8"))["status"] == "completed"


def test_faithfulness_evaluation_pipeline_recomputes_corrupted_completed_marker(tmp_path: Path) -> None:
    examples = example_records()
    run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
        trace_generator=RecordingTraceGenerator(),
        judge=RecordingJudge(),
        target_evaluator=RecordingTargetEvaluator(),
    )
    completed = tmp_path / "checkpoints" / "examples" / "scienceqa-test-1" / "completed.json"
    completed.write_text("{not-json", encoding="utf-8")

    trace_generator = RecordingTraceGenerator()
    judge = RecordingJudge()
    target_evaluator = RecordingTargetEvaluator()
    run_faithfulness_evaluation(
        examples=examples,
        output_dir=tmp_path,
        config={"dataset": "scienceqa", "target_model": "recording-target", "judge_model": "recording-judge"},
        trace_generator=trace_generator,
        judge=judge,
        target_evaluator=target_evaluator,
    )

    assert trace_generator.calls == 0
    assert judge.calls == 6
    assert target_evaluator.calls == 0


class FailingSecondExampleTraceGenerator(RecordingTraceGenerator):
    def __init__(self, failing_example_id: str) -> None:
        super().__init__()
        self.failing_example_id = failing_example_id

    def generate_trace(self, example) -> StructuredTrace:
        if example.example_id == self.failing_example_id:
            raise RuntimeError("simulated trace failure")
        return super().generate_trace(example)


class FailingSecondExampleTargetEvaluator(RecordingTargetEvaluator):
    def __init__(self, failing_example_id: str) -> None:
        super().__init__()
        self.failing_example_id = failing_example_id

    def evaluate(self, intervention_id, trace, example, condition="original_trace", include_image=True) -> TargetOutput:
        if example.example_id == self.failing_example_id:
            raise RuntimeError("simulated target failure")
        return super().evaluate(intervention_id, trace, example, condition=condition, include_image=include_image)


def _count_by_example_id(intervention_ids) -> dict[str, int]:
    counts: dict[str, int] = {}
    for intervention_id in intervention_ids:
        example_id = intervention_id.split("::")[0]
        counts[example_id] = counts.get(example_id, 0) + 1
    return counts


def example_records() -> list[Example]:
    return [
        Example(
            example_id="scienceqa-test-1",
            dataset="scienceqa",
            question="Which animal has a mouth adapted for bottom feeding?",
            choices={"A": "discus", "B": "armored catfish"},
            correct_answer="B",
            context="The image shows an animal with a downward-facing mouth.",
            image_path="/tmp/scienceqa-test-1.png",
            image_metadata={"has_image": True},
        ),
        Example(
            example_id="scienceqa-test-2",
            dataset="scienceqa",
            question="Which object casts a longer shadow?",
            choices={"A": "high light", "B": "low light"},
            correct_answer="B",
            context="The image shows a lower light angle.",
            image_path="/tmp/scienceqa-test-2.png",
            image_metadata={"has_image": True},
        ),
    ]
